---
:checking_acct: Checking
:savings_acct: Savings
:cash_acct: Cash
:current_assets: Assets
:qm:
  :name: Steven V Alex
  :address: 405 Karaway Hls
  :city: Gadsden AL, 35901
:post:
  :name: Wilson Parris
  :post: VFW Post 8600
  :numb: 8600
  :address: 817 Rainbow Dr
  :city: Gadsden AL, 35901
  :department: Alabama
:operations:
  - - a. Have required payroll deductions been made?
    - 'Yes'
  - - b. Have payments been made to the proper State & Federal agencies this quarter?
    - 'Yes'
  - - c. Have Sales Taxes been collected and paid?
    - 'Yes'
  - - d. Are Club employees bonded?
    - 'Yes'
  - - e. Amount of outstanding bills?
    - 0
  - - f. Value of Real Estate?
    - 0
  - - g. Amount of Liability Insurance?
    - 30000000
  - - h. Owed on Mortgages and Loans?
    - 0
  - - i. Value of Personal Property?
    - 1864900
  - - j. Amount of Property Insurance?
    - 0
:date: '2022-07-12'
:bond:
  :name: Tallman Insurance Agency
  :amount: 50000100
  :to: '2022-08-31'
:checking:
  :balance:  1815658
  :outstanding: 0
